---
- name: My Playbook
  hosts: localhost
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
      become: yes 

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present
      become: yes